routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/banned',function (){
    return view('ban');
});
Auth::routes();

Route::middleware('status')->get('/home', [Controllers\HomeController::class, 'index'])->name('home');
Route::middleware('status')->resource('doctor',Controllers\DoctorController::class);

Route::get('login/github', [Controllers\Auth\LoginController::class,'redirectToProvider'])->name('login.github');
Route::get('login/github/callback', [Controllers\Auth\LoginController::class,'handleProviderCallback']);
Route::group(['middleware'=>'doctorType'],function (){
    Route::group(['middleware'=>'DoctorProfile'],function(){
        Route::group(['middleware'=>'docValidity'],function (){
            Route::resource('doctor.appointment',Controllers\DocAppointmentController::class);
            Route::put('doctor/{docId}/appointment/{id}/accept',[Controllers\DocAppointmentController::class,'accept'])
                ->name('appointment.accept');
            Route::put('appointment/{id}/decline',[Controllers\DocAppointmentController::class,'decline'])
                ->name('appointment.decline');
            Route::get('doctor/appointment/search/{str}',[Controllers\DocAppointmentController::class,'search'])->name('appointment.search');
            Route::resource('doctor.forum',Controllers\DocForumController::class);
            Route::resource('doctor.forum.comment',Controllers\DocCommentController::class);
            //Route::resource('patient.docChatSession',Controllers\DocChatController::class);
            Route::get('doctor/{patient}/appointment/{aid}/chat',[Controllers\DocChatController::class,'index'])->name('docChat.index');
            Route::post('doctor/{patient}/appointment/{aid}/chat',[Controllers\DocChatController::class,'store'])->name('docChat.store');
            Route::get('chat/{patient}/getMessages',[Controllers\DocChatController::class,'getMessages']);
            Route::get('doctor/chatSession/patient/{id}/healthRecord',[Controllers\DocHealthRecordController::class,'index']);
            Route::post('doctor/{docId}/prescription',[Controllers\PrescriptionController::class,'store']);
            Route::put('session/{sid}/edit',[Controllers\SessionController::class,'update'])->name('doctor.chat.end');
            Route::get('doctor/{docId}/report/generate',[Controllers\DocReportGenController::class,'gen'])->name('doc.report.gen');
            Route::get('doctor/{docId}/report/earnings',[Controllers\DocTransactionController::class,'index'])->name('doc.earning.index');
            Route::get('doctor/{docId}/statistics/appointments',[App\Http\Controllers\DocAppointmentController::class,'stat'])->name('doc.stat.apt');
            Route::get('doctor/{docId}/statistics/generate',[App\Http\Controllers\DocReportGenController::class,'genStat'])->name('doc.stat.gen');


        });
        Route::get('doctor/{id}/invalid',[Controllers\DoctorController::class,'invalid'])->name('doctor.invalid');
    });
});



//admin

Route::group(['middleware'=>'adminType'],function (){
    Route::resource('admin',Controllers\AdminController::class);
    Route::resource('admin.userList',Controllers\UserListController::class);
    Route::resource('admin.doctorList', Controllers\DoctorListController::class);
    Route::resource('admin.subPlan',Controllers\SubplanController::class);
    Route::resource('admin.addStaff',Controllers\AddStaffController::class);
    Route::resource('admin.subscriptions',Controllers\SubscriptionController::class);
    Route::resource('admin.forum',Controllers\AdminForumController::class);
    Route::resource('admin.forum.comment',Controllers\AdminCommentController::class);
    Route::resource('admin.feedback',Controllers\FeedbackController::class);
    Route::get('userList/{userList}/delete/{id}',[Controllers\UserListController::class,'delete'])->name('userList.delete');
    Route::put('/admin/{admin}/doctorList/{doctorList}/ban/{id}',[Controllers\DoctorListController::class,'ban'])->name('doctorList.ban');
    Route::put('/admin/{admin}/doctorList/{doctorList}/valid/{id}',[Controllers\DoctorListController::class,'valid'])->name('doctorList.valid');
    Route::get('admin/{admin}/subReport/generate',[Controllers\SubscriptionController::class,'gen'])->name('admin.subReport.gen');
    Route::get('admin/{admin}/report/generate',[Controllers\FeedbackController::class,'gen'])->name('admin.report.gen');

});


//patients

Route::get('/patient',[App\Http\Controllers\PatientsController::class, 'index'])->name('patient.index');

Route::get('/patient/create',[App\Http\Controllers\PatientsController::class, 'create'])->name('patient.create');
Route::post('/patient/create',[App\Http\Controllers\PatientsController::class, 'store']);

Route::get('/patient/profile',[App\Http\Controllers\PatientsController::class, 'profile'])->name('patient.profile');

Route::get('/patient/appointment',[App\Http\Controllers\PatientsController::class, 'appointment'])->name('patient.appointment');
Route::post('/patient/appointment',[App\Http\Controllers\PatientsController::class, 'addReq']);
Route::get('/patient/appointment/{id}',[App\Http\Controllers\PatientsController::class, 'deleteReq'])->name('patient.deleteReq');
Route::get('/patient/pdf',[App\Http\Controllers\PatientsController::class, 'getList'])->name('patient.getList');

Route::get('/patient/docList',[App\Http\Controllers\PatientsController::class, 'docList'])->name('patient.docList');
Route::post('/patient/docList',[App\Http\Controllers\PatientsController::class, 'search']);

Route::get('/patient/prescriptions',[App\Http\Controllers\PatientsController::class, 'prescriptions'])->name('patient.prescriptions');
Route::get('/patient/prescriptions/{date}',[App\Http\Controllers\PatientsController::class, 'getPresc'])->name('patient.getPresc');

Route::get('/patient/subPlans',[App\Http\Controllers\PatientsController::class, 'subPlans'])->name('patient.subPlans');
Route::get('/patient/subPlans/{planId}',[App\Http\Controllers\PatientsController::class, 'editPlan'])->name('patient.editPlan');

Route::get('/patient/createRecord',[App\Http\Controllers\PatientsController::class, 'createRecord'])->name('patient.createRecord');
Route::post('/patient/createRecord',[App\Http\Controllers\PatientsController::class, 'insertRecord']);

Route::get('/patient/updateRecord',[App\Http\Controllers\PatientsController::class, 'updateRecord'])->name('patient.updateRecord');
Route::post('/patient/updateRecord',[App\Http\Controllers\PatientsController::class, 'editRecord']);

Route::get('/patient/updateProfile',[App\Http\Controllers\PatientsController::class, 'updateProfile'])->name('patient.updateProfile');
Route::post('/patient/updateProfile',[App\Http\Controllers\PatientsController::class, 'editProfile']);

Route::get('/patient/changePassword',[App\Http\Controllers\PatientsController::class, 'changePassword'])->name('patient.changePassword');
Route::post('/patient/changePassword',[App\Http\Controllers\PatientsController::class, 'updatePassword']);


//staff

Route::group(['middleware'=>'staffType'],function (){
    Route::resource('staff',\App\Http\Controllers\StaffController::class);
    Route::resource('staff.userList',\App\Http\Controllers\StaffUserListController::class);
    Route::resource('staff.doctorList',\App\Http\Controllers\StaffDoctorListController::class);
    Route::get('userList/{userList}/delete/{id}',[App\Http\Controllers\StaffUserListController::class,'delete'])->name('userList.delete');
    Route::resource('staff.forum',\App\Http\Controllers\StaffForumController::class);
    Route::resource('staff.forum.comment',\App\Http\Controllers\StaffCommentController::class);
    Route::resource('staff.feedback',\App\Http\Controllers\StaffFeedbackController::class);
    Route::put('/staff/{staff}/doctorList/{doctorList}/ban/{id}',[App\Http\Controllers\StaffDoctorListController::class,'ban'])->name('doctorList.ban');


});

app/Models/Doctor.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Doctor extends Model
{
    use HasFactory;
}

app/Http/Controllers/DoctorController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\DoctorRequests;
use App\Http\Requests\DoctorUpdateRequests;
use App\Models\Doctor;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class DoctorController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');

    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //print_r(Auth::user());
        $doctor=DB::table('doctors')
            ->rightJoin('users','doctors.userId','=','users.id')
            ->where('userId','=',Auth::user()->id)
            ->get();
        //print_r($doctor);
        if(count($doctor)) {
            if($request->session()->has('docId')==false){
                $doc=DB::table('doctors')
                    ->where('userId','=',Auth::user()->id)
                    ->get()[0];
                $request->session()->put('docId',$doc->id);
            }
            //dd($doctor);
            //echo $request->session()->get('docId');
            return view('doctor.index')->with('user', $doctor[0]);
        }
        else {
            $request->session()->flash('msg','Please Complete Your Profile');
            return redirect()->route('doctor.create');
        }

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $doctor=DB::table('doctors')
            ->where('userId','=',Auth::user()->id)
            ->get();
        //print_r($doctor);
        if(count($doctor)==0){
            $request->session()->flash('msg','Please Complete Your Profile');
            return view('doctor.create');
        }
        else{
            return redirect()->route('doctor.index');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(DoctorRequests $request)
    {
        $doctor=new Doctor();
        $doctor->phone=$request->phone;
        $doctor->gender=$request->gender;
        $doctor->license=$request->license;
        $doctor->qualifications=$request->qualifications;
        $doctor->specialty=$request->specialty;
        $doctor->userId=Auth::user()->id;

        if($request->hasFile('photo')){
            $file=$request->file('photo');
//            echo "File Name: ". $file->getClientOriginalName()."<br>";
//            echo "File Extension: ". $file->getClientOriginalExtension()."<br>";
//            echo "File Size: ". $file->getSize()."<br>";
//            echo "File Mime Type: ". $file->getMimeType();
            $filename=$file->getClientOriginalName();

            if($file->move('img', $filename)){
                $doctor->photo=$filename;
                $doctor->save();
                return redirect()->route('doctor.index');
            }
            else{
                return redirect()->route('doctor.create');
            }
        }
        else{
            echo 'Profile photo is not selected';
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Doctor  $doctor
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request,Doctor $doctor)
    {
        $doctor=DB::table('doctors')
            ->where('userId','=',Auth::user()->id)
            ->get();
        //print_r($doctor);
        if(count($doctor)) {

            return view('doctor.index')->with('user', $doctor[0]);
        }
        else {
            $request->session()->flash('msg','Please Complete Your Profile');
            return redirect()->route('doctor.create');
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Doctor  $doctor
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request,$doctor)
    {
        $doc=DB::table('doctors')
            ->where('userId','=',$doctor)
            ->get();
        //print_r($doctor);
        if(count($doc)) {
            $doc=DB::table('users')
                ->leftJoin('doctors','users.id','=','doctors.userId')
                ->where('userId',$doctor)
                ->get();
            return view('doctor.edit')->with('user', $doc[0]);
        }
        else {
            $request->session()->flash('msg','Please Complete Your Profile');
            return redirect()->route('doctor.create');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Doctor  $doctor
     * @return \Illuminate\Http\Response
     */
    public function update(DoctorUpdateRequests $request, $doctor)
    {
        $user=User::find($doctor);
        $doctor=Doctor::find($request->session()->get('docId'));
        if($request->password!=null && $request->new_password!=null){
            if(Hash::check($request->password,$user->password)){
                if(strlen($request->new_password)>=8) {
                    $user->password = Hash::make($request->new_password);
                }
                else{
                    $request->session()->flash('msg','Password Should be longer than 8 characters');
                    return redirect()->route('doctor.edit',Auth::user()->id);
                }
            }
            else{
                $request->session()->flash('msg','Incorrect current password');
                return redirect()->route('doctor.edit',Auth::user()->id);
            }

        }
        $user->name=$request->name;
        $doctor->phone=$request->phone;
        $doctor->gender=$request->gender;
        $doctor->license=$request->license;
        $doctor->qualifications=$request->qualifications;
        $doctor->specialty=$request->specialty;

        if($request->hasFile('photo')){
            $file=$request->file('photo');
//            echo "File Name: ". $file->getClientOriginalName()."<br>";
//            echo "File Extension: ". $file->getClientOriginalExtension()."<br>";
//            echo "File Size: ". $file->getSize()."<br>";
//            echo "File Mime Type: ". $file->getMimeType();
            $filename=$file->getClientOriginalName();

            if($file->move('img', $filename)){
                $doctor->photo=$filename;

            }

        }
        //dd($request);
        $user->save();
        $doctor->save();
        return redirect()->route('doctor.index');


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Doctor  $doctor
     * @return \Illuminate\Http\Response
     */
    public function destroy(Doctor $doctor)
    {
        //
    }

    public function invalid(Request $request){
        return view('doctor.invalid');
    }
}

resources/views/doctor/create.blade.php
@extends('layouts.doctor')

@section('content')
    <div class="container mt-2">
        <div class="row">
            <div class="col-12 col-md-6 offset-md-3">
                <div class="card shadow-sm">
                    <div class="card-header">
                        <div class="text-center">
                            <div class="h5 text-danger">
                                {{session('msg')}}
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{{route('doctor.store')}}" enctype="multipart/form-data">
                            @csrf

                            <div class="row">
                                <div class="col-12 col-md-4">
                                    <div class="form-group">
                                        <label for="phone"><strong>Phone:</strong></label>
                                        <input type="text" class="form-control" name="phone"
                                               id="phone" placeholder="Phone" value="{{old('phone')}}"/>
                                    </div>
                                </div>

                                <div class="col-12 col-md-3">
                                    <div class="form-group">
                                        <label for="gender"><strong>Gender:</strong></label>
                                        <select class="form-control" name="gender" id="gender">
                                            <option selected>Male</option>
                                            <option>Female</option>
                                            <option>Other</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-12 col-md-5">
                                    <div class="form-group">
                                        <label for="license"><strong>License:</strong></label>
                                        <input type="text" class="form-control" name="license"
                                               id="license" placeholder="License Number" value="{{old('license')}}"/>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="qualifications"><strong>Qualifications:</strong></label>
                                <textarea class="form-control" name="qualifications" value="{{old('qualifications')}}"
                                          id="qualifications" placeholder="Educational Qualifications"></textarea>
                            </div>
                            <div class="row">

                                <div class="col-12">
                                    <div class="form-group">
                                        <label for="specialty"><strong>Specialty:</strong></label>
                                        <select class="form-control" name="specialty" id="specialty">
                                            <option selected>Addiction Psychology</option>
                                            <option>Biopsychology</option>
                                            <option>Cognitive Psychology</option>
                                            <option>Counseling Psychology</option>
                                            <option>Developmental Psychology</option>
                                            <option>Educational Psychology</option>
                                            <option>Experimental Psychology</option>
                                            <option>Forensic Psychology</option>
                                            <option>Health Psychology</option>
                                            <option>Human Factors Psychology</option>
                                            <option>Industrial Psychology</option>
                                            <option>Media Psychology</option>
                                            <option>Military Psychology</option>
                                            <option>Pediatric Psychology</option>
                                            <option>Social Psychology</option>
                                            <option>Sport Psychology</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="photo"><strong>Profile Picture:</strong></label>
                                <input type="file" class="form-control-file" name="photo" id="photo" accept="image/*">
                            </div>
                            <div class="row">
                                 <div class=" col-12 text-center">
                                    <input type="submit" class="btn btn-primary pr-3 pl-3" value="Submit" id="submit"/>
                                </div>
                            </div>


                        </form>
                    </div>
                </div>

            </div>
            <div class="col-auto">
            </div>
        </div>
        <div class="row">
            <div class="col-12 offset-sm-2 col-sm-8 text-danger">
                @foreach($errors->all() as $err)
                    {{$err}} <br>
                @endforeach
            </div>
        </div>
    </div>

@endsection

resources/views/doctor/edit.blade.php
@extends('layouts.doctor')

@section('content')
    <div class="container mt-2">
        <div class="row">
            <div class="col-12 col-md-6 offset-md-3">
                <div class="card shadow-sm">
                    <div class="card-header">
                        <div class="text-center">
                            <div class="h5">
                                Edit Profile
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{{route('doctor.update',Auth::User()->id)}}" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')

                            <div class="row">
                                <div class="col-12 col-md-6">
                                    <div class="form-group">
                                        <label for="name"><strong>Name:</strong></label>
                                        <input type="text" class="form-control" name="name"
                                               id="name" placeholder="name" value="{{$user->name}}"/>
                                    </div>
                                </div>
                                <div class="col-12 col-md-6">
                                    <div class="form-group">
                                        <label for="phone"><strong>Phone:</strong></label>
                                        <input type="text" class="form-control" name="phone"
                                               id="phone" placeholder="Phone" value="{{$user->phone}}"/>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-12 col-md-6">
                                    <div class="form-group">
                                        <label for="new_password"><strong>New Password:</strong></label>
                                        <input type="text" class="form-control" name="new_password"
                                               id="new_password" placeholder="New Password"/>
                                    </div>
                                </div>

                                <div class="col-12 col-md-6">
                                    <div class="form-group">
                                        <label for="password"><strong>Current Password:</strong></label>
                                        <input type="text" class="form-control" name="password"
                                               id="password" placeholder="Current Password"/>

                                    </div>
                                </div>

                            </div>

                            <div class="row">

                                <div class="col-12 col-md-6">
                                    <div class="form-group">
                                        <label for="gender"><strong>Gender:</strong></label>
                                        <select class="form-control" name="gender" id="gender">
                                            <option selected hidden>{{$user->gender}}</option>
                                            <option>Male</option>
                                            <option>Female</option>
                                            <option>Other</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-12 col-md-6">
                                    <div class="form-group">
                                        <label for="license"><strong>License:</strong></label>
                                        <input type="text" class="form-control" name="license"
                                               id="license" placeholder="License Number" value="{{$user->license}}"/>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="qualifications"><strong>Qualifications:</strong></label>
                                <textarea class="form-control" name="qualifications"
                                          id="qualifications" placeholder="Educational Qualifications">{{$user->qualifications}}</textarea>
                            </div>
                            <div class="row">

                                <div class="col-12">
                                    <div class="form-group">
                                        <label for="specialty"><strong>Specialty:</strong></label>
                                        <select class="form-control" name="specialty" id="specialty">
                                            <option selected hidden>{{$user->specialty}}</option>
                                            <option>Addiction Psychology</option>
                                            <option>Biopsychology</option>
                                            <option>Cognitive Psychology</option>
                                            <option>Counseling Psychology</option>
                                            <option>Developmental Psychology</option>
                                            <option>Educational Psychology</option>
                                            <option>Experimental Psychology</option>
                                            <option>Forensic Psychology</option>
                                            <option>Health Psychology</option>
                                            <option>Human Factors Psychology</option>
                                            <option>Industrial Psychology</option>
                                            <option>Media Psychology</option>
                                            <option>Military Psychology</option>
                                            <option>Pediatric Psychology</option>
                                            <option>Social Psychology</option>
                                            <option>Sport Psychology</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="photo"><strong>Profile Picture:</strong></label>
                                <input type="file" class="form-control-file" name="photo" id="photo" accept="image/*">
                            </div>
                            <div class="row">
                                <div class=" col-12 text-center">
                                    <input type="submit" class="btn btn-primary pr-3 pl-3" value="Submit" id="submit"/>
                                </div>
                            </div>


                        </form>
                    </div>
                </div>

            </div>
            <div class="col-auto">
                <div class="text-danger">
                    @foreach($errors->all() as $err)
                        {{$err}} <br>
                    @endforeach
                    {{session('msg')}}
                </div>
            </div>
        </div>
    </div>
@endsection