routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/banned',function (){
    return view('ban');
});
Auth::routes();

Route::middleware('status')->get('/home', [Controllers\HomeController::class, 'index'])->name('home');
Route::middleware('status')->resource('doctor',Controllers\DoctorController::class);

Route::get('login/github', [Controllers\Auth\LoginController::class,'redirectToProvider'])->name('login.github');
Route::get('login/github/callback', [Controllers\Auth\LoginController::class,'handleProviderCallback']);
Route::group(['middleware'=>'doctorType'],function (){
    Route::group(['middleware'=>'DoctorProfile'],function(){
        Route::group(['middleware'=>'docValidity'],function (){
            Route::resource('doctor.appointment',Controllers\DocAppointmentController::class);
            Route::put('doctor/{docId}/appointment/{id}/accept',[Controllers\DocAppointmentController::class,'accept'])
                ->name('appointment.accept');
            Route::put('appointment/{id}/decline',[Controllers\DocAppointmentController::class,'decline'])
                ->name('appointment.decline');
            Route::get('doctor/appointment/search/{str}',[Controllers\DocAppointmentController::class,'search'])->name('appointment.search');
            Route::resource('doctor.forum',Controllers\DocForumController::class);
            Route::resource('doctor.forum.comment',Controllers\DocCommentController::class);
            //Route::resource('patient.docChatSession',Controllers\DocChatController::class);
            Route::get('doctor/{patient}/appointment/{aid}/chat',[Controllers\DocChatController::class,'index'])->name('docChat.index');
            Route::post('doctor/{patient}/appointment/{aid}/chat',[Controllers\DocChatController::class,'store'])->name('docChat.store');
            Route::get('chat/{patient}/getMessages',[Controllers\DocChatController::class,'getMessages']);
            Route::get('doctor/chatSession/patient/{id}/healthRecord',[Controllers\DocHealthRecordController::class,'index']);
            Route::post('doctor/{docId}/prescription',[Controllers\PrescriptionController::class,'store']);
            Route::put('session/{sid}/edit',[Controllers\SessionController::class,'update'])->name('doctor.chat.end');
            Route::get('doctor/{docId}/report/generate',[Controllers\DocReportGenController::class,'gen'])->name('doc.report.gen');
            Route::get('doctor/{docId}/report/earnings',[Controllers\DocTransactionController::class,'index'])->name('doc.earning.index');
            Route::get('doctor/{docId}/statistics/appointments',[App\Http\Controllers\DocAppointmentController::class,'stat'])->name('doc.stat.apt');
            Route::get('doctor/{docId}/statistics/generate',[App\Http\Controllers\DocReportGenController::class,'genStat'])->name('doc.stat.gen');


        });
        Route::get('doctor/{id}/invalid',[Controllers\DoctorController::class,'invalid'])->name('doctor.invalid');
    });
});



//admin

Route::group(['middleware'=>'adminType'],function (){
    Route::resource('admin',Controllers\AdminController::class);
    Route::resource('admin.userList',Controllers\UserListController::class);
    Route::resource('admin.doctorList', Controllers\DoctorListController::class);
    Route::resource('admin.subPlan',Controllers\SubplanController::class);
    Route::resource('admin.addStaff',Controllers\AddStaffController::class);
    Route::resource('admin.subscriptions',Controllers\SubscriptionController::class);
    Route::resource('admin.forum',Controllers\AdminForumController::class);
    Route::resource('admin.forum.comment',Controllers\AdminCommentController::class);
    Route::resource('admin.feedback',Controllers\FeedbackController::class);
    Route::get('userList/{userList}/delete/{id}',[Controllers\UserListController::class,'delete'])->name('userList.delete');
    Route::put('/admin/{admin}/doctorList/{doctorList}/ban/{id}',[Controllers\DoctorListController::class,'ban'])->name('doctorList.ban');
    Route::put('/admin/{admin}/doctorList/{doctorList}/valid/{id}',[Controllers\DoctorListController::class,'valid'])->name('doctorList.valid');
    Route::get('admin/{admin}/subReport/generate',[Controllers\SubscriptionController::class,'gen'])->name('admin.subReport.gen');
    Route::get('admin/{admin}/report/generate',[Controllers\FeedbackController::class,'gen'])->name('admin.report.gen');

});


//patients

Route::get('/patient',[App\Http\Controllers\PatientsController::class, 'index'])->name('patient.index');

Route::get('/patient/create',[App\Http\Controllers\PatientsController::class, 'create'])->name('patient.create');
Route::post('/patient/create',[App\Http\Controllers\PatientsController::class, 'store']);

Route::get('/patient/profile',[App\Http\Controllers\PatientsController::class, 'profile'])->name('patient.profile');

Route::get('/patient/appointment',[App\Http\Controllers\PatientsController::class, 'appointment'])->name('patient.appointment');
Route::post('/patient/appointment',[App\Http\Controllers\PatientsController::class, 'addReq']);
Route::get('/patient/appointment/{id}',[App\Http\Controllers\PatientsController::class, 'deleteReq'])->name('patient.deleteReq');
Route::get('/patient/pdf',[App\Http\Controllers\PatientsController::class, 'getList'])->name('patient.getList');

Route::get('/patient/docList',[App\Http\Controllers\PatientsController::class, 'docList'])->name('patient.docList');
Route::post('/patient/docList',[App\Http\Controllers\PatientsController::class, 'search']);

Route::get('/patient/prescriptions',[App\Http\Controllers\PatientsController::class, 'prescriptions'])->name('patient.prescriptions');
Route::get('/patient/prescriptions/{date}',[App\Http\Controllers\PatientsController::class, 'getPresc'])->name('patient.getPresc');

Route::get('/patient/subPlans',[App\Http\Controllers\PatientsController::class, 'subPlans'])->name('patient.subPlans');
Route::get('/patient/subPlans/{planId}',[App\Http\Controllers\PatientsController::class, 'editPlan'])->name('patient.editPlan');

Route::get('/patient/createRecord',[App\Http\Controllers\PatientsController::class, 'createRecord'])->name('patient.createRecord');
Route::post('/patient/createRecord',[App\Http\Controllers\PatientsController::class, 'insertRecord']);

Route::get('/patient/updateRecord',[App\Http\Controllers\PatientsController::class, 'updateRecord'])->name('patient.updateRecord');
Route::post('/patient/updateRecord',[App\Http\Controllers\PatientsController::class, 'editRecord']);

Route::get('/patient/updateProfile',[App\Http\Controllers\PatientsController::class, 'updateProfile'])->name('patient.updateProfile');
Route::post('/patient/updateProfile',[App\Http\Controllers\PatientsController::class, 'editProfile']);

Route::get('/patient/changePassword',[App\Http\Controllers\PatientsController::class, 'changePassword'])->name('patient.changePassword');
Route::post('/patient/changePassword',[App\Http\Controllers\PatientsController::class, 'updatePassword']);


//staff

Route::group(['middleware'=>'staffType'],function (){
    Route::resource('staff',\App\Http\Controllers\StaffController::class);
    Route::resource('staff.userList',\App\Http\Controllers\StaffUserListController::class);
    Route::resource('staff.doctorList',\App\Http\Controllers\StaffDoctorListController::class);
    Route::get('userList/{userList}/delete/{id}',[App\Http\Controllers\StaffUserListController::class,'delete'])->name('userList.delete');
    Route::resource('staff.forum',\App\Http\Controllers\StaffForumController::class);
    Route::resource('staff.forum.comment',\App\Http\Controllers\StaffCommentController::class);
    Route::resource('staff.feedback',\App\Http\Controllers\StaffFeedbackController::class);
    Route::put('/staff/{staff}/doctorList/{doctorList}/ban/{id}',[App\Http\Controllers\StaffDoctorListController::class,'ban'])->name('doctorList.ban');


});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{asset('css/all.css')}}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md text-white bg-dark bg-dark shadow-sm">
            <div class="container">
                <a class="navbar-brand text-white" href="{{ url('/') }}">
                    {{ config('app.name', 'Mental Health Counseling System') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link text-white" href="{{ route('login') }}"><i class="fa fa-sign-in-alt"></i> {{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link text-white" href="{{ route('register') }}"><i class="fa fa-user-plus"></i> {{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    <i class="fa fa-user"></i> {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        <i class="fa fa-sign-out"></i> {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/doctor.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->

{{--    <link href="{{asset('css/bootstrap.css')}}" rel="stylesheet">--}}
{{--    <script src="{{asset('js/jquery.js')}}" defer type="application/javascript"></script>--}}
{{--    <script src="{{asset('js/popper.js')}}" defer type="application/javascript"></script>--}}
{{--    <script src="{{ asset('js/bootstrap.js') }}" type="application/javascript"></script>--}}
    <script src="{{asset('js/app.js')}}" defer></script>
    <script src="{{asset('js/docScript.js')}}" defer type="application/javascript"></script>
{{--    <script src="{{asset('js/docForumScript.js')}}" defer type="application/javascript"></script>--}}

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{asset('css/all.css')}}" rel="stylesheet">

</head>
<body>
<div id="app">
    <nav class="navbar navbar-expand-md sticky-top text-white bg-dark shadow-sm">
        <div class="container">
            <a class="navbar-brand text-white" href="{{ route('doctor.index') }}">
                {{ config('app.name', 'Mental Health Counseling System') }}
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>



            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->

                <form class="form-inline mr-auto d-inline text-center w-75">
                    @csrf
                    <input class="form-control mr-sm-2 w-75" type="search" id="searchText" placeholder="Search Appointments by patient" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit" id="search" data-toggle="tooltip" data-placement="bottom" title="Search"><i class="fa fa-search"></i></button>
                </form>

                <ul class="navbar-nav mr-auto">

                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    <!-- Authentication Links -->
                    @guest
                        <li class="nav-item text-nowrap">
                            <a class="nav-link text-white" href="{{ route('login') }}"><i class="fa fa-sign-in"></i> {{ __('Login') }}</a>
                        </li>
                        @if (Route::has('register'))
                            <li class="nav-item text-nowrap">
                                <a class="nav-link text-white" href="{{ route('register') }}"><i class="fa fa-sign"></i> {{ __('Register') }}</a>
                            </li>
                        @endif
                    @else
                        <li class="nav-item text-nowrap">
                            <a class="nav-link text-white" href="{{route('doctor.index')}}"><i class="fa fa-home"></i> Home</a>
                        </li>
                        <li class="nav-item text-nowrap">
                            <a class="nav-link text-white" href="{{route('doctor.appointment.index',Auth::user()->id)}}"><i class="fa fa-list"></i> Appointments</a>
                        </li>
                        <li class="nav-item text-nowrap dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle text-white" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                <i class="fa fa-user"></i> {{ Auth::user()->name }}
                            </a>


                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a id="ddDropdown" class="dropdown-item dropdown-toggle text-dark" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    <i class="fa fa-user-cog"></i> {{ __('Profile settings') }}
                                </a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="ddDropdown">
                                    <a class="dropdown-item text-dark" href="{{route('doctor.edit',Auth::User()->id)}}"><i class="fa fa-user-edit"></i> {{__('Edit Profile')}}</a>
                                    <a class="dropdown-item text-dark" href="#"><i class="fa fa-user-minus"></i> {{__('Delete Profile')}}</a>
                                </div>
                                <a class="dropdown-item text-dark" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    <i class="fa fa-sign-out-alt"></i> {{ __('Logout') }}
                                </a>


                                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                    @csrf
                                </form>
                            </div>
                        </li>
                        <li class="nav-item dropdown text-nowrap">
                            <a id="moreDropdown" class=" nav-link dropdown-toggle text-white" href="#"
                               role="button" data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false"
                               v-pre>
                                <i class="fas fa-ellipsis-h" data-toggle="tooltip" data-placement="right" title="More options"></i>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="moreDropdown">
                                <a class="dropdown-item text-dark" href="#"><i class="fa fa-comment"></i> {{__('Chat')}}</a>
                                <a class="dropdown-item text-dark" href="{{route('doctor.forum.index',Auth::user()->id)}}"><i class="fa fa-sticky-note"></i> {{__('Forum')}}</a>
                                <a class="dropdown-item text-dark" href="{{route('doc.earning.index',Auth::user()->id)}}"><i class="fa fa-money-check-alt"></i> Earning Report</a>
                                <a class="dropdown-item text-dark" href="{{route('doc.stat.apt',Auth::user()->id)}}"><i class="fa fa-file-alt"></i> Appointment Statistics</a>
                            </div>
                        </li>

                    @endguest
                </ul>
            </div>
        </div>
    </nav>


                <div class="modal fade" id="searchModal" tabindex="-1" aria-labelledby="searchLabel" aria-hidden="true">
                    <div class="modal-dialog modal-xl modal-dialog-centered">
                        <div class="modal-content">
                            <div class="modal-header bg-secondary text-white">
                                <h5 class="modal-title" id="searchLabel"></h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body text-left">
                                <div id="appointmentItems" class="text-center">

                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>


    <main class="py-4">
        @yield('content')
    </main>

</div>
</body>
</html>